apiVersion: v1
kind: Service
metadata:
  name: salary-prediction-service1
spec:
  selector:
    app: salary-prediction1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
